name: geSuitAdmin
main : au.com.addstar.geSuitAdmin.geSuitAdmin
version: ${plugin.version}
api-version: ${spigot.api.version}
author: Narimm
description: Part of the geSuit (gesuit) this plugin allows admin to perform network wide server specific restarts from proxy
commands:
  gesuitdebug:
    usage: /<command>
    description: Turn on debugging.
    permission: geSuit.admin