name: ${project.artifactId}
main : au.com.addstar.geSuitAdmin.geSuitAdmin
version: ${plugin.version}
api-version: ${spigot.api.version}
author: Narimm
description: ${project.description}
commands:
  gesuitdebug:
    usage: /<command>
    description: Turn on debugging.
    permission: geSuit.admin