name: geSuitBans
main : net.cubespace.geSuitBans.geSuitBans
version: ${project.version}b-${build.number}
api-version: ${spigot.api.verison}
description: Part of the geSuit this plugin allows moderators to ban and kick players
author: narimm
commands:
    ban:
        description: Bans a player from the proxy
        aliases: [banplayer,db]
        permission: gesuit.bans.command.ban
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command> (player)
               /<command> (player) (message)
    warn:
        description: Issues an official warning to a player
        aliases: [warnplayer,dw]
        permission: gesuit.bans.command.warn
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command> (player)
               /<command> (player) (message)
    checkban:
        description: Gets info about a players ban
        aliases: [lookupban,baninfo]
        permission: gesuit.bans.command.checkban
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    banhistory:
        description: Gets the ban history of a player
        permission: gesuit.bans.command.banhistory
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    warnhistory:
        description: Gets the warning history of a player
        aliases: [dst, warnings]
        permission: gesuit.bans.command.warnhistory
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    where:
        description: Gets the login history of IPs, players and UUIDs
        aliases: [wherehistory]
        permission: gesuit.bans.command.where
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    ontime:
        description: Gets the ontime statistics of a player
        permission: gesuit.bans.command.ontime
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)|((top) (page))
    lastlogins:
        description: Gets the last logins of a player
        permission: gesuit.bans.command.lastlogins
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player) (number to return)
    ipban:
        description: Bans an IP from the proxy
        aliases: [banip,dbip]
        permission: gesuit.bans.command.ipban
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command> (player)
               /<command> (ip)
               /<command> (ip/player) (message)
    kick:
        description: Kick a player from the proxy
        aliases: [kickplayer, playerkick, kickp,pkick]
        permission: gesuit.bans.command.kick
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command> (player)
               /<command> (player) (message)
    kickall:
        description: Kicks everyone from the proxy
        aliases: [kicka]
        permission: gesuit.bans.command.kickall
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command>
               /<command> (message)
    lockdown:
        description: locks the server so no new players can join
        permission: gesuit.ban.command.lockdown
        permission-message: §cYou do not have permission for this command
        usage: /<command> end|status|<time> <msg>
    reloadbans:
        description: Reloads the bans config
        aliases: [bansreload, reloadban, banreload]
        permission: gesuit.bans.command.reload
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    tempban:
        description: Temporarily bans a player from the proxy
        aliases: [tban,bant,bantemp,dtb]
        permission: gesuit.bans.command.tempban
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command> (player) (time) (reason)
               /<command> (player) (time) (reason)        
               Example: /command bob 2d5h building things
               Valid time units: s (seconds), m (minutes),
               h (hours), d (days) and w (weeks)
    unban:
        description: Unbans a player from the proxy
        aliases: [uban,removeban,pardon,dub]
        permission: gesuit.bans.command.ban
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    unipban:
        description: Unbans an IP from the proxy
        aliases: [ipunban,unbanip,ipsafe,safeip,dubip]
        permission: gesuit.bans.command.ipban
        permission-message: §cYou do not have permission for this command
        usage: /<command> (ip)
    namehistory:
        description: Gets the name history of a player
        aliases: [names]
        permission: gesuit.bans.command.namehistory
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    newspawn:
        description: Forces a player to the new spawn
        permission: gesuit.bans.command.newspawn
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
permissions:
    gesuit.bans.*:
        description: Gives access to all bans commands
        default: op
        children:
            gesuit.chat.admin: true
    gesuit.bans.admin:
        description: Gives access to all bans admin commands
        children:
            gesuit.bans.command.kickall: true
            gesuit.bans.command.ipban: true
            gesuit.bans.command.reload: true
            gesuit.bans.mod: true
            gesuit.bans.command.lockdown: true
    gesuit.bans.mod:
        description: Gives access to all bans mod commands
        children:
            gesuit.bans.command.ban: true
            gesuit.bans.command.checkban: true
            gesuit.bans.command.banhistory: true
            gesuit.bans.command.kick: true
            gesuit.bans.command.tempban: true
            gesuit.bans.command.namehistory: true
